### ISSUE TITLE
[performance] slow on some file

### ISSUE THREAD

**Issue by whitedogg13** [revtel/.vim#6]
how to reproduct:

1. clone RN CLI repo: https://github.com/react-native-community/cli
2. try to edit `/packages/cli/src/commands/init/init.ts`

**Comment by guychienll** [comment]
the issues seem like the syntax highlight performance issue. will continue to observe.

**Comment by guychienll** [comment]
hi @whitedogg13 
I can't reproduce after I do a lots of commit , so I don't know what the step make it work , but I think the issue was solved , ridiculously 🤣 
Maybe you could pull the latest version to solved this issue.

**Comment by whitedogg13** [comment]
@guychienll yep, it's running much faster now!
