### ISSUE TITLE
Illegal argument: ctermul=red

### ISSUE THREAD

**Issue by whitedogg13** [revtel/.vim#7]
Error screenshot:
![image](https://user-images.githubusercontent.com/10307875/103456696-9d243a00-4d33-11eb-9f66-aa2342807a18.png)

Not familier with `ctermul`, this config seems appear after Vim version 8.2.863?
* https://www.gitmemory.com/issue/vim/vim/6174/636869793

My vim (builtin with MacOS BigSur), seems not include this patch. Here's the `vim --version` result:
![image](https://user-images.githubusercontent.com/10307875/103456748-073cdf00-4d34-11eb-81e1-d77cd8f8425d.png)

Havn't try to upgrade Vim yet, however I think if others do report this, mayb we can consider to remove these configs from `plugin/ale.vim`, so our vim config works with builtin version.

**Comment by guychienll** [comment]
Ok , I would try to replace it to reach the same feature ! I will remove it ASAP !

**Comment by guychienll** [comment]
remove it
