### ISSUE TITLE
checkout to new branch to support vim version below 8.1 ( include ) [ legacy ]

### ISSUE THREAD

**Issue by guychienll** [revtel/.vim#9]
@whitedogg13 @ChienHsiao 
There is the new branch for support vim below 8.1 ( include )
I think the root cause is the plugin `utilsnips` , because it depends on python3 ,
so I remove it and it will effect the feature about postfix completion .
and the issue we talk about can not finished install step , I can not reproduce it .
My computer built in vim is 8.1 depends on python , and I use the latest version 8.2 depends on python3 .
I use these two version to install , still can not reproduce it ,
so I think the issue maybe occur on the vim version below 8.1 .
thanks !

- built in version of my OS
![image](https://user-images.githubusercontent.com/63462677/104470545-c9be3880-55f4-11eb-86b9-a167ce74e222.png)

- the latest version of vim
![image](https://user-images.githubusercontent.com/63462677/104470568-cdea5600-55f4-11eb-8bc1-ffc140b7431c.png)

**Comment by guychienll** [comment]
If apply success , can close issue ! thanks !

**Comment by whitedogg13** [comment]
@guychienll Just confirm the legacy branch works well, thanks
